services:
  app.services.user:
    class: App\Service\UserService
    arguments:
      - '@app.repositories.user'

  app.services.invitation:
    class: App\Service\InvitationService
    arguments:
      - '@app.repositories.invitation'
      - '@app.services.user'
